[project]
name = "rag-practice-arxiv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipywidgets>=8.1.8",
    "jupyterlab>=4.5.3",
    "jupytext>=1.19.1",
    "kaleido>=1.2.0",
    "langchain>=1.2.9",
    "langgraph>=1.0.8",
    "numpy>=2.4.2",
    "pandas>=2.3.3",
    "plotly>=6.5.2",
    "polars>=1.38.1",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.0",
    "streamlit>=1.54.0",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "nbqa>=1.9.1",
    "nbstripout>=0.9.0",
    "pandas-stubs>=3.0.0.260204",
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "ruff>=0.15.0",
]

[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM"]

[tool.ruff.lint.isort]
known-first-party = ["rag_practice_arxiv"]

[tool.jupytext]
formats = "notebooks///ipynb,notebooks///py:percent"

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
